import { QrCode } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { usePDF } from "react-to-pdf";
import { QRCodeSVG } from "qrcode.react";
import { useState } from "react";

export default function TicketCard() {
  const [ticketID, setTicketID] = useState(32322);
  const { toPDF, targetRef } = usePDF({ filename: `Ticket - ${ticketID}.pdf` });

  return (
    <div>
      <Card className="col-span-1" ref={targetRef}>
        <CardContent className="p-0">
          {/* Header Image */}
          <div className="relative h-56 bg-[#2A1B3D] overflow-hidden">
            <div className="absolute inset-0 p-6">
              <div className="relative z-10 space-y-2">
                <div className="flex items-center gap-2">
                  <div className="px-3 py-1 bg-[#E84545]/90 text-white text-xs rounded-full">
                    SUMMIT
                  </div>
                </div>
                <h2 className="text-white text-2xl font-bold leading-tight">
                  East India
                  <br />
                  Blockchain Summit 2025
                </h2>
                <p>
                    <span className="text-[#ffffffb0]">East India's Largest <br /> Blockchain Hackathon</span>
                    <br />
                </p>
              </div>
            </div>
            {/* Decorative musical notes pattern */}
            <div className="absolute inset-0 opacity-20">
              {[...Array(6)].map((_, i) => (
                <div
                  key={i}
                  className="absolute transform rotate-45 w-8 h-8 border-2 border-white/30"
                  style={{
                    left: `${Math.random() * 100}%`,
                    top: `${Math.random() * 100}%`,
                  }}
                />
              ))}
            </div>
          </div>

          {/* Ticket Details */}
          <div className="p-6 space-y-6">
            <table className="w-full text-left text-sm border border-gray-300">
              <tbody>
                <tr className="border-b border-gray-300">
                  <td className="p-2 font-medium">Attendee Name</td>
                  <td className="p-2">Ridwan Soleh</td>
                </tr>
                <tr className="border-b border-gray-300">
                  <td className="p-2 font-medium">Attendee Email</td>
                  <td className="p-2">
                    <a
                      href="mailto:clickswarnendu123@gmail.com"
                      className="underline"
                    >
                      clickswarnendu123@gmail.com
                    </a>
                  </td>
                </tr>
                <tr className="border-b border-gray-300">
                  <td className="p-2 font-medium">Location</td>
                  <td className="p-2">The Park, Jakarta, Indonesia</td>
                </tr>
                <tr>
                  <td className="p-2 font-medium">Time</td>
                  <td className="p-2">9 PM - 12 PM</td>
                </tr>
              </tbody>
            </table>

            {/* QR Code */}
            <div className="flex justify-center">
              <div className="p-4 bg-white rounded-lg shadow-md">
                <QRCodeSVG
                  value="https://example.com/ticket/32322"
                  size={128}
                  level="H"
                  includeMargin={true}
                />
              </div>
            </div>

            <p className="text-xs text-center text-gray-500">
              Ticket ID: {ticketID}
            </p>
            <p className="text-[10px]">
              Generated by{" "}
              <a href="https://evnt.press" className="underline">
                evnt.press
              </a>{" "}
              at {new Date().toLocaleString()}
            </p>
          </div>
        </CardContent>
      </Card>
      <Button onClick={() => toPDF()} className="mt-6 w-full">
        Download Ticket
      </Button>
    </div>
  );
}
