export const EventData = [
    {
      name: "ETH India 2025",
      org_name: "ETH Global",
      date: "Jul 2, 2024",
      registration: "Open",
      registration_fee: 0,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBlQAxuIO7pj06XiNdJrG32J8emLvjOC0nJQ&s",
      registered: 300,
      location: "Bangalore",
    },
    {
      name: "DeFi Summit 2024",
      org_name: "DeFi Alliance",
      date: "Aug 15, 2024",
      registration: "Open",
      registration_fee: 50,
      image: "https://file.chainup.com/pub/2024-07-23/13e88637-37ba-4959-9a29-3ad1e7d0dc63.webp",
      registered: 150,
      location: "San Francisco",
    },
    {
      name: "Blockchain Expo",
      org_name: "Blockchain Association",
      date: "Sep 20, 2024",
      registration: "Closed",
      registration_fee: 100,
      image: "https://agcdn-1d97e.kxcdn.com/wp-content/uploads/2020/09/alphagamma-Blockchain-Expo-opportunites-1021x580.jpg",
      registered: 500,
      location: "New York",
    },
    {
      name: "NFT Connect 2024",
      org_name: "NFT Global",
      date: "Oct 5, 2024",
      registration: "Open",
      registration_fee: 25,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZaQWd1AHIhUAPUsES4UGyVhVzVKjZJQi_SA&s",
      registered: 200,
      location: "Tokyo",
    },
    {
      name: "Web3 Hackathon",
      org_name: "Hackathon Central",
      date: "Nov 12, 2024",
      registration: "Open",
      registration_fee: 0,
      image: "https://cse.noticebard.com/wp-content/uploads/sites/23/2023/04/Web3-Hackathon-2023-1024x535.jpg",
      registered: 350,
      location: "London",
    },
    {
      name: "CryptoCon 2024",
      org_name: "CryptoCon Team",
      date: "Dec 1, 2024",
      registration: "Closed",
      registration_fee: 75,
      image: "https://res.cloudinary.com/eduardsi/image/upload/w_1000,c_fit,co_white,l_text:Lato_80_bold:Cryptocon%25202024,g_north_west,x_100,y_100/w_1000,c_fit,co_white,l_text:Lato_40:May%252010-11%25202024,g_north_west,x_100,y_360/w_1000,c_fit,co_white,l_text:Lato_40_bold:New%2520York%252C%2520United%2520States,g_north_west,x_100,y_430/devevents-og_o00xcs.png",
      registered: 400,
      location: "Singapore",
    },
    {
      name: "Metaverse Summit",
      org_name: "Metaverse Alliance",
      date: "Jan 25, 2025",
      registration: "Open",
      registration_fee: 30,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT4Yp8BaBICC7TBdeSMgTkoBTnIO693Ieyzg&s",
      registered: 220,
      location: "Dubai",
    },
    {
      name: "DAO Builders Meetup",
      org_name: "DAO Collective",
      date: "Feb 18, 2025",
      registration: "Open",
      registration_fee: 0,
      image: "http://localhost:5173/src/assets/ethindia.png",
      registered: 180,
      location: "Berlin",
    },
    {
      name: "Smart Contracts Workshop",
      org_name: "DevChain Academy",
      date: "Mar 14, 2025",
      registration: "Open",
      registration_fee: 40,
      image: "http://localhost:5173/src/assets/ethindia.png",
      registered: 250,
      location: "Sydney",
    },
    {
      name: "AI & Blockchain Conference",
      org_name: "Tech Synergy",
      date: "Apr 22, 2025",
      registration: "Closed",
      registration_fee: 120,
      image: "http://localhost:5173/src/assets/ethindia.png",
      registered: 420,
      location: "Paris",
    }
  ];
  